#Cargo.toml
[package]
name = "brick-draw"
version = "0.1.0"
description = "Desktop drawing application built with Tauri and Rust."
authors = ["Plynte Labs"]
edition = "2021"
license = "MIT"
repository = "https://github.com/plynte-labs/brick-draw"
keywords = ["tauri", "graphics", "wgpu", "canvas", "drawing"]
categories = ["gui", "graphics"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "brick_draw_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
# Tauri & Core Plugins
tauri = { version = "2.0.0", features = ["test"] }
tauri-plugin-opener = "2.0.0"
tauri-plugin-dialog = "2.0.0"
parking_lot = "0.12"
zip = { version = "8.6", default-features = false, features = ["deflate"] }


# Data & Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts-rs = "12.0"

# Graphics & Rendering Engine
wgpu = "30.0" 
# winit = "0.29"    # Para gestionar los eventos de la ventana nativa
tiny-skia = "0.12" # Opcional: Para dibujar en la CPU muy rápido sobre un buffer native
image = "0.25"

[dev-dependencies]
dhat = "0.3"

[features]
dhat-heap = []

