// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerMetadataDto = { id: string, name: string, opacity: number, visible: boolean, locked: boolean, x: number, y: number, width: number, height: number, };