// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured result returned to the frontend so it can re-sync whatever the op touched.
 * `kind` is a discriminant: the frontend `applyUndoResult` dispatches on it. The pixel path keeps
 * master's behaviour (re-pull the layer PNG); structural ops carry the metadata needed to patch
 * the Zustand store without an IPC round-trip.
 */
export type UndoResult = { 
/**
 * One of: "pixel" | "move" | "opacity" | "visibility" | "delete" | "reorder" | "selection".
 */
kind: string, 
/**
 * Affected layer id (empty for reorder/selection where it is not a single layer).
 */
layer_id: string, 
/**
 * For "move": the resulting position. For "delete"-restore: the reinserted layer position.
 */
x: number | null, y: number | null, 
/**
 * For "opacity".
 */
opacity: number | null, 
/**
 * For "visibility".
 */
visible: boolean | null, 
/**
 * For "delete": z-order index where the layer was (re)inserted.
 */
index: number | null, 
/**
 * For "delete": whether the layer now EXISTS (true = it was reinserted by undo; false = it was
 * removed by redo). Lets the frontend add or drop the layer accordingly.
 */
layer_exists: boolean | null, 
/**
 * For "delete"-restore: layer width/height so the frontend can rebuild its OffscreenCanvas.
 */
width: number | null, height: number | null, 
/**
 * For "delete"-restore: the active layer id after restore.
 */
active_layer_id: string | null, 
/**
 * For "reorder": the full id list in the new z-order.
 */
order: Array<string> | null, };